### ISSUE TITLE
facade.require doesn't work in titanium-Android

### ISSUE THREAD

**Issue by kt3k** [CureApp/base-domain#46]
https://github.com/CureApp/base-domain/blob/9bfd74950282a3a92aef60b5cce06ef95587b8dc/src/lib/util.coffee#L67

This check seems always returning false in titanium/Android environment.

Maybe the relationship between the resource path and the script path is different from titanium/iPhone architecture.

**Comment by shinout** [comment]
Thanks for the report. I didn't check this function in titanium/Android. The solution will be the following;

- if not Ti? then requires path
- if Ti then path is added ".js" suffix
- if Android then requires path
- if iOS then checks the existence and requires path after checking passes
